### ISSUE TITLE
More comments in the settings.conf file

### ISSUE THREAD

**Issue by pst019** [dennissergeev/pmctrack#26]
Hi Denis,
[settings_ERA5.zip](https://github.com/dennissergeev/pmctrack/files/3916492/settings_ERA5.zip)

I added more comments to my version of the settings.conf file. This makes it more easy for me and possibly other new users, to understand the different parameters.
Maybe you want to include them into your default version.

I have also some questions:
- what are variables: int_zeta_min0, merge_opt?
- how is the surrounding for exclusion of the extratropical cyclones calculated?
- what is the unit for del_psea_min? (we have different pressure units)
- would it make sense to define the parameters for the cold front exclusion in the conf file?

I also give some suggestions for renaming some variables to follow your article and thesis more closely.

Best,
Patrick

**Comment by dennissergeev** [comment]
Hey Patrick,

I agree some of the parameter names are quite cryptic, thanks for raising this issue. And thanks for attaching an updated version of `settings.conf`. It would be much better if you can do it via a pull request please (sorry to nag you about it). Also note that the file does not allow blank lines, so they all should start with the comment symbol (`#`).

Regarding your questions:
 - `int_zeta_min0` is the interval for increasing `ζmin` (s^-1); `merge_opt` is what parameter is used to define a dominant vortex when two vortices are merged together: `merge_opt=1` is by distance (as in Watanabe's original code), while `merge_opt=2` is by vortex size ([source code](https://github.com/dennissergeev/pmctrack/blob/master/src/link_vort_rad.f90#L206))
- I don't quite follow what you mean by surrounding for exclusion, but the algorithm is described in Sec. 2-b-3 of https://journals.ametsoc.org/doi/full/10.1175/MWR-D-15-0349.1
- `del_psea_min` is in hPa. I should've mentioned that these parameters are listed with units in `docs/Readme.docx`.
> would it make sense to define the parameters for the cold front exclusion in the conf file?
- Absolutely. If you are willing to move them to `params.f90` and `settings.conf`, it would be absolutely awesome (via a pull request). If you don't have to do it, let me know what parameters you want to be moved.

**Comment by pst019** [comment]
Hi Denis,
I did not do it via pull request since my settings.config file is running on somewhat different input data. If you anyway think I should do a pull request, I can do so.

Thanks for your answers.
- Regarding my second question: Watanabe (2016) write "First, the sizes of
the original vortex areas are examined and SLP minima that are at least 0.5 hPa less than the surroundings are detected." I could not find a more specific description of the surrounding. Is it the mean within 300km radius or something comparable?

- I posed the question considering del_psea_min since msl is in Pa in my files. I could not find that the code is translating this to hPa. I also asked since 0.5hPa seem to be a very small threshold which is likely always satisfied. Did you do some tests with it?

- I will see if I manage to move the front parameters.

**Comment by dennissergeev** [comment]
> I did not do it via pull request since my settings.config file is running on somewhat different input data. 

What you can do is you can create a local copy of `settings.conf` and call it e.g. `my_settings.conf` and run the algorithm by typing `./track.x my_settings.conf`. Then you can keep the original settings file clean and commit only important changes rather than your local settings.

> If you anyway think I should do a pull request, I can do so.

No pressure, but it would be much appreciated :)

> Is it the mean within 300km radius or something comparable?

This is how Shun-ichi puts it: "In the code, first, a local SLP minimum is detected. Then, the minimum
SLP is compared with the largest closed contour of SLP that encloses the SLP minimum. The SLP minimum is accepted if the difference is larger than 0.5 hPa." The detection is made within 300 km.

>  since msl is in Pa in my files.

My data (and sample data) is also in Pa. It gets converted to hPa on [this line](https://github.com/dennissergeev/pmctrack/blob/master/src/main.f90#L255) and so eventually data in hPa of this field are being compared to `del_psea_min` in hPa too. I haven't done any sensitivity tests though.

**Comment by dennissergeev** [comment]
Configuration file improvements addressed in #30

Automatic Pa to hPa conversion addressed in 8677e53cb740b7200595d4ced25261504d428049
